### ISSUE TITLE
Sync Options Flag

### ISSUE THREAD

**Issue by Kanti** [phpsu/phpsu#34]
- [ ] --remove-old / --delete ...
- [x] --no-db / --without-database #47
- [x] --no-file(s) / --without-files #47
- [x] --all (--without-excludes) #46

**Comment by Kanti** [comment]
all implemented except for --delete, which is kept in #56
